apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "moscow-time-app.fullname" . }}
  labels:
    {{- include "moscow-time-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "moscow-time-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "moscow-time-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: internal-app
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: MY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: MY_SECRET
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config